services:
  backend:
    build:
      context: ./server
    container_name: backend-fastify
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./infrastructure/logging/logs/app.log:/app/app.log
      - ./server/code/backend-fastify/database.sqlite:/app/database.sqlite
    networks:
      - elk-net

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=search
      - xpack.security.enrollment.enabled=true
      - xpack.security.http.ssl.enabled=false
    ports:
      - 9200:9200
    networks:
      - elk-net
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esconfig:/usr/share/elasticsearch/config

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elk-net
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=kibanasser
      - ELASTICSEARCH_PASSWORD=search
    volumes:
      - kibdata:/usr/share/kibana/data

  logstash:
    image: logstash:8.12.0
    container_name: logstash
    volumes:
      - ./infrastructure/logging/logs/app.log:/usr/share/logstash/logs/app.log
      - ./infrastructure/logging/logs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk-net
    depends_on:
      - elasticsearch

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./infrastructure/performance/k6-script.js:/k6-script.js
      - ./infrastructure/performance/k6-script-db-test.js:/k6-script-db-test.js  
    networks:
      - elk-net
    entrypoint: ["sleep", "infinity"]
    depends_on:
      - backend

networks:
  elk-net:
    driver: bridge

volumes:
  esdata:
  kibdata:
  esconfig: