services:
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=search
    ports:
      - 9200:9200
    networks:
      - elk-net
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elk-net
    depends_on:
      - elasticsearch
    volumes:
      - kibdata:/usr/share/kibana/data

  logstash:
    image: logstash:8.12.0
    container_name: logstash
    volumes:
      - ./logs/app.log:/usr/share/logstash/logs/app.log
      - ./logs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk-net
    depends_on:
      - elasticsearch

networks:
  elk-net:
    driver: bridge

volumes:
  esdata:
  kibdata:

# Commands to run after starting the stack:
# docker exec elasticsearch bin/elasticsearch-create-enrollment-token -s kibana
# copy and paste token on localhost:5601
# docker exec kibana bin/kibana-verification-code
# copy and paste code
# docker exec -it elasticsearch bin/elasticsearch-reset-password -u elastic --interactive
# set new password, confirm new password, and login
# on 'Discover' tab: input the index pattern (fastify-logs-*)
